### ISSUE TITLE
RV errors are calculated potentially incorrectly

### ISSUE THREAD

**Issue by gmbrandt** [LCOGT/banzai-nres#51]
https://github.com/LCOGT/banzai-nres/blob/aa18ad98ba8c4566d9688128757b9147adbd5f12/banzai_nres/rv.py#L126

RV errors are calculated from the full array of rv's per order, while the RV is calculated from a sigma clipped array. We need to calculate the distribution of the RV results from the included orders only.

robust standard devation is just the median absolute deviation times a constant, but may not equal the standard deviation of the sigma clipped result.

E.g. we could replace the tagged lines with 
`rv, mask = stats.sigma_clipped_mean(rvs_per_order, 3.0) * 1000`
 `rv_err = np.std(rvs_per_order[mask]) * 1000`

**Comment by captain-exoplanet** [comment]
We have now modified the code to eliminate this issue. The RVs and RV errors are now calculated from the same sigma-clipped array:

`rv, rv_err = np.ma.mean(rvs_per_order), np.ma.std(rvs_per_order) / np.sqrt(np.ma.count(rvs_per_order))`
